import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Account = { id: number; name: string; currency: string; openingBalance: number; active: boolean }
type Category = { id: number; name: string; type: 'Income' | 'Expense'; active: boolean }
type PlannedTransaction = { id: number; date: string; amount: number; fromAccountId: number | null; toAccountId: number | null; categoryId: number | null; recurringRuleId: number | null; description: string | null; cancelled: boolean }
type RecurringRule = { id: number; name: string; amount: number; frequency: string; startDate: string; endDate: string | null; active: boolean; description: string | null }
type Transaction = { id: number; date: string; amount: number; fromAccountId: number | null; toAccountId: number | null; categoryId: number | null; description: string | null; transactionType: 'INCOME' | 'EXPENSE' | 'TRANSFER' }
type Form = { fromAccountId: string; toAccountId: string; categoryId: string; description: string; amount: string; date: string }
type PlannedForm = Form
type RecurringForm = { name: string; amount: string; fromAccountId: string; toAccountId: string; categoryId: string; frequency: string; dayOfMonth: string; startDate: string; endDate: string; description: string }
const API_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:5140/api'
const emptyForm: Form = { fromAccountId: '', toAccountId: '', categoryId: '', description: '', amount: '', date: new Date().toISOString().slice(0, 10) }

function periodBounds(period: string) { const [year, month] = period.split('-').map(Number); const lastDay = new Date(year, month, 0).getDate(); return { from: `${period}-01`, to: `${period}-${String(lastDay).padStart(2, '0')}` } }
function shiftPeriod(period: string, offset: number) { const [year, month] = period.split('-').map(Number); const absolute = year * 12 + month - 1 + offset; return `${Math.floor(absolute / 12)}-${String((absolute % 12) + 1).padStart(2, '0')}` }
async function request<T>(path: string, options?: RequestInit): Promise<T> { const response = await fetch(`${API_URL}${path}`, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!response.ok) throw new Error(await response.text() || `Request failed (${response.status})`); return response.status === 204 ? undefined as T : response.json() }

function App() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [planned, setPlanned] = useState<PlannedTransaction[]>([]); const [recurring, setRecurring] = useState<RecurringRule[]>([]); const [activeView, setActiveView] = useState('Transactions');
  const [period, setPeriod] = useState(() => new Date().toISOString().slice(0, 7)); const [filter, setFilter] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [showTransaction, setShowTransaction] = useState(false); const [showAccount, setShowAccount] = useState(false); const [editingId, setEditingId] = useState<number | null>(null); const [editingAccountId, setEditingAccountId] = useState<number | null>(null); const [form, setForm] = useState<Form>(emptyForm); const [accountName, setAccountName] = useState(''); const [currency, setCurrency] = useState('EUR'); const [openingBalance, setOpeningBalance] = useState('0'); const [saving, setSaving] = useState(false)
  const [showPlanned, setShowPlanned] = useState(false); const [showRecurring, setShowRecurring] = useState(false); const [showCategory, setShowCategory] = useState(false); const [plannedForm, setPlannedForm] = useState<PlannedForm>(emptyForm); const [recurringForm, setRecurringForm] = useState<RecurringForm>({ name: '', amount: '', fromAccountId: '', toAccountId: '', categoryId: '', frequency: 'Monthly', dayOfMonth: '', startDate: new Date().toISOString().slice(0, 10), endDate: '', description: '' }); const [categoryName, setCategoryName] = useState(''); const [categoryType, setCategoryType] = useState('Expense')
  const loadData = async () => { setLoading(true); setError(''); try { const [loadedAccounts, loadedCategories, loadedTransactions, loadedPlanned, loadedRecurring] = await Promise.all([request<Account[]>(`/accounts?includeInactive=${activeView === 'Accounts'}`), request<Category[]>('/categories'), request<Transaction[]>(`/transactions?from=${periodBounds(period).from}&to=${periodBounds(period).to}${filter ? `&type=${filter}` : ''}`), request<PlannedTransaction[]>(`/planning/planned-transactions?from=${periodBounds(period).from}&to=${periodBounds(period).to}`), request<RecurringRule[]>('/planning/recurring-rules')]); setAccounts(loadedAccounts); setCategories(loadedCategories); setTransactions(loadedTransactions); setPlanned(loadedPlanned); setRecurring(loadedRecurring) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load data.') } finally { setLoading(false) } }
  useEffect(() => { void loadData() }, [period, filter, activeView])
  const money = new Intl.NumberFormat('en-IE', { style: 'currency', currency: accounts[0]?.currency ?? 'EUR' }); const accountNameFor = (id: number | null) => accounts.find(account => account.id === id)?.name ?? 'External account'
  const openNewTransaction = () => { setEditingId(null); setForm({ ...emptyForm, toAccountId: accounts[0] ? String(accounts[0].id) : '' }); setShowTransaction(true) }
  const openEditTransaction = (item: Transaction) => { setEditingId(item.id); setForm({ fromAccountId: String(item.fromAccountId ?? ''), toAccountId: String(item.toAccountId ?? ''), categoryId: String(item.categoryId ?? ''), description: item.description ?? '', amount: String(item.amount), date: item.date }); setShowTransaction(true) }
  const saveTransaction = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await request(`/transactions${editingId ? `/${editingId}` : ''}`, { method: editingId ? 'PUT' : 'POST', body: JSON.stringify({ date: form.date, amount: Number(form.amount), fromAccountId: form.fromAccountId ? Number(form.fromAccountId) : null, toAccountId: form.toAccountId ? Number(form.toAccountId) : null, categoryId: form.categoryId ? Number(form.categoryId) : null, plannedTransactionId: null, description: form.description || null }) }); setShowTransaction(false); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save transaction.') } finally { setSaving(false) } }
  const deleteTransaction = async (item: Transaction) => { if (!window.confirm(`Delete “${item.description ?? 'transaction'}”?`)) return; try { await request(`/transactions/${item.id}`, { method: 'DELETE' }); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not delete transaction.') } }
  const saveAccount = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const path = editingAccountId ? `/accounts/${editingAccountId}` : '/accounts'; const method = editingAccountId ? 'PUT' : 'POST'; await request(path, { method, body: JSON.stringify(editingAccountId ? { name: accountName, currency, openingBalance: Number(openingBalance), active: true } : { name: accountName, currency, openingBalance: Number(openingBalance) }) }); setShowAccount(false); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save account.') } finally { setSaving(false) } }
  const openNewAccount = () => { setEditingAccountId(null); setAccountName(''); setCurrency('EUR'); setOpeningBalance('0'); setShowAccount(true) }; const openEditAccount = (account: Account) => { setEditingAccountId(account.id); setAccountName(account.name); setCurrency(account.currency); setOpeningBalance(String(account.openingBalance)); setShowAccount(true) }
  const deactivate = async (account: Account) => { if (!window.confirm(`Deactivate “${account.name}”?`)) return; await request(`/accounts/${account.id}`, { method: 'DELETE' }); await loadData() }
  const closeForms = () => { if (!saving) { setShowTransaction(false); setShowAccount(false); setShowPlanned(false); setShowRecurring(false); setShowCategory(false) } }
  useEffect(() => {
    document.querySelectorAll<HTMLFormElement>('form.modal').forEach(modal => {
      if (modal.querySelector('.modal-inline-close') || modal.querySelector('.close-button')) return
      const closeButton = document.createElement('button')
      closeButton.className = 'close-button modal-inline-close'
      closeButton.type = 'button'
      closeButton.setAttribute('aria-label', 'Close')
      closeButton.textContent = '×'
      closeButton.addEventListener('click', closeForms)
      const title = modal.querySelector(':scope > h2')
      const heading = document.createElement('div')
      heading.className = 'modal-heading'
      if (title) heading.appendChild(title)
      heading.appendChild(closeButton)
      modal.prepend(heading)
    })
  }, [showTransaction, showAccount])
  const savePlanned = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await request('/planning/planned-transactions', { method: 'POST', body: JSON.stringify({ date: plannedForm.date, amount: Number(plannedForm.amount), fromAccountId: plannedForm.fromAccountId ? Number(plannedForm.fromAccountId) : null, toAccountId: plannedForm.toAccountId ? Number(plannedForm.toAccountId) : null, categoryId: plannedForm.categoryId ? Number(plannedForm.categoryId) : null, recurringRuleId: null, description: plannedForm.description || null }) }); setShowPlanned(false); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save planned transaction.') } finally { setSaving(false) } }
  const saveRecurring = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await request('/planning/recurring-rules', { method: 'POST', body: JSON.stringify({ name: recurringForm.name, amount: Number(recurringForm.amount), fromAccountId: recurringForm.fromAccountId ? Number(recurringForm.fromAccountId) : null, toAccountId: recurringForm.toAccountId ? Number(recurringForm.toAccountId) : null, categoryId: recurringForm.categoryId ? Number(recurringForm.categoryId) : null, frequency: recurringForm.frequency, dayOfMonth: recurringForm.dayOfMonth ? Number(recurringForm.dayOfMonth) : null, startDate: recurringForm.startDate, endDate: recurringForm.endDate || null, description: recurringForm.description || null }) }); setShowRecurring(false); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save recurring rule.') } finally { setSaving(false) } }
  const saveCategory = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await request('/categories', { method: 'POST', body: JSON.stringify({ name: categoryName, type: categoryType }) }); setCategoryName(''); setShowCategory(false); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save category.') } finally { setSaving(false) } }
  const income = transactions.filter(item => item.transactionType === 'INCOME').reduce((sum, item) => sum + item.amount, 0); const expense = transactions.filter(item => item.transactionType === 'EXPENSE').reduce((sum, item) => sum + item.amount, 0)

  return <div className={`app-shell ${activeView.toLowerCase()}`}>{(showTransaction || showAccount) && <button className="modal-global-close" onClick={closeForms} type="button" aria-label="Close form">×</button>}
    <aside className="sidebar"><div className="brand"><span className="brand-mark">F</span><span>finplanner</span></div><nav aria-label="Main navigation">{['Transactions', 'Planned', 'Recurring', 'Categories', 'Accounts'].map(item => <button className={activeView === item ? 'nav-item active' : 'nav-item'} key={item} onClick={() => setActiveView(item)} type="button"><span className="nav-icon">{item === 'Transactions' ? '↕' : item === 'Planned' ? '◷' : item === 'Recurring' ? '↻' : item === 'Categories' ? '◉' : '◫'}</span>{item}</button>)}</nav></aside>
    <main className="main-content"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> {activeView}</div>{activeView === 'Accounts' && <button className="add-button" onClick={openNewAccount} type="button"><span>+</span> Add account</button>}{activeView === 'Transactions' && <button className="add-button" onClick={openNewTransaction} type="button"><span>+</span> Add transaction</button>}{activeView === 'Planned' && <button className="add-button" onClick={() => { setPlannedForm({ ...emptyForm, toAccountId: accounts[0] ? String(accounts[0].id) : '' }); setShowPlanned(true) }} type="button"><span>+</span> Add planned</button>}{activeView === 'Recurring' && <button className="add-button" onClick={() => setShowRecurring(true)} type="button"><span>+</span> Add recurring rule</button>}{activeView === 'Categories' && <button className="add-button" onClick={() => setShowCategory(true)} type="button"><span>+</span> Add category</button>}</header>
      <div className="content-wrap"><section className="page-heading"><div><p className="eyebrow">Household activity</p><h1>{activeView}</h1><p className="muted">{activeView === 'Accounts' ? 'Manage accounts from the final database model.' : 'Actual transactions from your planned and unplanned activity.'}</p></div>{activeView === 'Transactions' && <div className="period-controls"><button className="month-arrow" onClick={() => setPeriod(current => shiftPeriod(current, -1))} aria-label="Previous month" type="button">‹</button><input aria-label="Month" type="month" value={period} onChange={event => setPeriod(event.target.value)} /><button className="month-arrow" onClick={() => setPeriod(current => shiftPeriod(current, 1))} aria-label="Next month" type="button">›</button><select aria-label="Transaction type" value={filter} onChange={event => setFilter(event.target.value)}><option value="">All types</option><option value="Income">Income</option><option value="Expense">Expenses</option></select></div>}</section>
        {error && <div className="error-banner" role="alert">{error}</div>}
        {activeView === 'Transactions' ? <><section className="metric-grid"><article className="metric-card"><div className="metric-top"><span>Income</span></div><strong>{money.format(income)}</strong></article><article className="metric-card"><div className="metric-top"><span>Expenses</span></div><strong>{money.format(expense)}</strong></article><article className="metric-card"><div className="metric-top"><span>Net</span></div><strong>{money.format(income - expense)}</strong></article><article className="metric-card"><div className="metric-top"><span>Actual transactions</span></div><strong>{transactions.length}</strong></article></section><section className="panel transaction-panel"><div className="panel-heading"><div><h2>Actual transactions</h2><p className="muted">{period} · {transactions.length} records</p></div></div>{loading ? <p className="empty-state">Loading...</p> : !transactions.length ? <div className="empty-state"><strong>No actual transactions</strong><button className="add-button" onClick={openNewTransaction} type="button">+ Add transaction</button></div> : <div className="transaction-list">{transactions.map(item => <div className="transaction" key={item.id}><span className="transaction-icon green">{item.transactionType[0]}</span><span className="transaction-info"><strong>{item.description ?? 'No description'}</strong><small>{item.transactionType} · {accountNameFor(item.fromAccountId)} → {accountNameFor(item.toAccountId)} · {item.date}</small></span><strong className={item.transactionType === 'INCOME' ? 'amount income-amount' : 'amount'}>{item.transactionType === 'EXPENSE' ? '-' : '+'}{money.format(item.amount)}</strong><button className="row-action" onClick={() => openEditTransaction(item)} type="button" aria-label="Edit transaction">✎</button><button className="row-action danger" onClick={() => void deleteTransaction(item)} type="button" aria-label="Delete transaction">×</button></div>)}</div>}</section></> : <section className="panel account-panel"><div className="panel-heading"><div><h2>Accounts</h2><p className="muted">{accounts.length} accounts</p></div><button className="link-button" onClick={openNewAccount} type="button">Add account +</button></div>{accounts.map(account => <div className="account-row" key={account.id}><span className="account-badge">{account.name[0]}</span><span className="transaction-info"><strong>{account.name}</strong><small>{account.currency} · opening {money.format(account.openingBalance)} · {account.active ? 'Active' : 'Inactive'}</small></span><button className="row-action" onClick={() => openEditAccount(account)} type="button">✎</button>{account.active && <button className="row-action danger" onClick={() => void deactivate(account)} type="button">×</button>}</div>)}</section>}
        <section className={`panel model-panel planned-panel ${activeView === 'Planned' ? 'visible-panel' : ''}`}><div className="panel-heading"><div><h2>Planned transactions</h2><p className="muted">{planned.length} planned items for {period}</p></div></div>{planned.length ? <div className="transaction-list">{planned.map(item => <div className="transaction" key={item.id}><span className="transaction-icon yellow">P</span><span className="transaction-info"><strong>{item.description ?? 'Planned transaction'}</strong><small>{item.date} · {item.cancelled ? 'Cancelled' : item.recurringRuleId ? 'Recurring' : 'One-time'}</small></span><strong className="amount">{money.format(item.amount)}</strong></div>)}</div> : <p className="empty-state">No planned transactions for this month.</p>}</section>
        <section className={`panel model-panel recurring-panel ${activeView === 'Recurring' ? 'visible-panel' : ''}`}><div className="panel-heading"><div><h2>Recurring rules</h2><p className="muted">{recurring.length} rules</p></div></div>{recurring.length ? <div className="transaction-list">{recurring.map(item => <div className="transaction" key={item.id}><span className="transaction-icon blue">↻</span><span className="transaction-info"><strong>{item.name}</strong><small>{item.frequency} · from {item.startDate}{item.endDate ? ` to ${item.endDate}` : ''} · {item.active ? 'Active' : 'Inactive'}</small></span><strong className="amount">{money.format(item.amount)}</strong></div>)}</div> : <p className="empty-state">No recurring rules configured.</p>}</section>
        <section className={`panel model-panel categories-panel ${activeView === 'Categories' ? 'visible-panel' : ''}`}><div className="panel-heading"><div><h2>Categories</h2><p className="muted">{categories.length} active categories</p></div></div>{categories.length ? <div className="transaction-list">{categories.map(category => <div className="transaction" key={category.id}><span className={`transaction-icon ${category.type === 'Income' ? 'yellow' : 'green'}`}>{category.type[0]}</span><span className="transaction-info"><strong>{category.name}</strong><small>{category.type} · {category.active ? 'Active' : 'Inactive'}</small></span></div>)}</div> : <p className="empty-state">No categories configured.</p>}</section>
      </div></main>
    {showTransaction && <div className="modal-backdrop"><form className="modal" onSubmit={saveTransaction}><h2>{editingId ? 'Edit actual transaction' : 'Add actual transaction'}</h2><label>Description<input value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /></label><div className="form-row"><label>Amount<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={event => setForm({ ...form, amount: event.target.value })} /></label><label>Date<input required type="date" value={form.date} onChange={event => setForm({ ...form, date: event.target.value })} /></label></div><div className="form-row"><label>From account<select value={form.fromAccountId} onChange={event => setForm({ ...form, fromAccountId: event.target.value })}><option value="">External</option>{accounts.filter(account => account.active).map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label><label>To account<select value={form.toAccountId} onChange={event => setForm({ ...form, toAccountId: event.target.value })}><option value="">External</option>{accounts.filter(account => account.active).map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label></div><label>Category<select value={form.categoryId} onChange={event => setForm({ ...form, categoryId: event.target.value })}><option value="">No category</option>{categories.map(category => <option value={category.id} key={category.id}>{category.name} ({category.type})</option>)}</select></label><button className="add-button full" disabled={saving} type="submit">{saving ? 'Saving...' : 'Save transaction'}</button></form></div>}
    {showAccount && <div className="modal-backdrop"><form className="modal" onSubmit={saveAccount}><h2>{editingAccountId ? 'Edit account' : 'Add account'}</h2><label>Name<input required value={accountName} onChange={event => setAccountName(event.target.value)} /></label><div className="form-row"><label>Currency<input required minLength={3} maxLength={3} value={currency} onChange={event => setCurrency(event.target.value.toUpperCase())} /></label><label>Opening balance<input min="0" step="0.01" type="number" value={openingBalance} onChange={event => setOpeningBalance(event.target.value)} /></label></div><button className="add-button full" disabled={saving} type="submit">{saving ? 'Saving...' : 'Save account'}</button></form></div>}
    {showPlanned && <div className="modal-backdrop"><form className="modal" onSubmit={savePlanned}><div className="modal-heading"><h2>Add planned transaction</h2><button className="close-button" onClick={closeForms} type="button" aria-label="Close">×</button></div><label>Description<input value={plannedForm.description} onChange={event => setPlannedForm({ ...plannedForm, description: event.target.value })} /></label><div className="form-row"><label>Amount<input required min="0.01" step="0.01" type="number" value={plannedForm.amount} onChange={event => setPlannedForm({ ...plannedForm, amount: event.target.value })} /></label><label>Date<input required type="date" value={plannedForm.date} onChange={event => setPlannedForm({ ...plannedForm, date: event.target.value })} /></label></div><div className="form-row"><label>From account<select value={plannedForm.fromAccountId} onChange={event => setPlannedForm({ ...plannedForm, fromAccountId: event.target.value })}><option value="">External</option>{accounts.filter(account => account.active).map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label><label>To account<select value={plannedForm.toAccountId} onChange={event => setPlannedForm({ ...plannedForm, toAccountId: event.target.value })}><option value="">External</option>{accounts.filter(account => account.active).map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label></div><label>Category<select value={plannedForm.categoryId} onChange={event => setPlannedForm({ ...plannedForm, categoryId: event.target.value })}><option value="">No category</option>{categories.map(category => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><button className="add-button full" disabled={saving} type="submit">{saving ? 'Saving...' : 'Save planned transaction'}</button></form></div>}
    {showRecurring && <div className="modal-backdrop"><form className="modal" onSubmit={saveRecurring}><div className="modal-heading"><h2>Add recurring rule</h2><button className="close-button" onClick={closeForms} type="button" aria-label="Close">×</button></div><label>Name<input required value={recurringForm.name} onChange={event => setRecurringForm({ ...recurringForm, name: event.target.value })} /></label><label>Description<input value={recurringForm.description} onChange={event => setRecurringForm({ ...recurringForm, description: event.target.value })} /></label><div className="form-row"><label>Amount<input required min="0.01" step="0.01" type="number" value={recurringForm.amount} onChange={event => setRecurringForm({ ...recurringForm, amount: event.target.value })} /></label><label>Frequency<select value={recurringForm.frequency} onChange={event => setRecurringForm({ ...recurringForm, frequency: event.target.value })}><option value="Daily">Daily</option><option value="Weekly">Weekly</option><option value="Monthly">Monthly</option><option value="Yearly">Yearly</option></select></label></div><div className="form-row"><label>Start date<input required type="date" value={recurringForm.startDate} onChange={event => setRecurringForm({ ...recurringForm, startDate: event.target.value })} /></label><label>Day of month<input min="1" max="31" type="number" value={recurringForm.dayOfMonth} onChange={event => setRecurringForm({ ...recurringForm, dayOfMonth: event.target.value })} /></label></div><div className="form-row"><label>From account<select value={recurringForm.fromAccountId} onChange={event => setRecurringForm({ ...recurringForm, fromAccountId: event.target.value })}><option value="">External</option>{accounts.filter(account => account.active).map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label><label>To account<select value={recurringForm.toAccountId} onChange={event => setRecurringForm({ ...recurringForm, toAccountId: event.target.value })}><option value="">External</option>{accounts.filter(account => account.active).map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label></div><button className="add-button full" disabled={saving} type="submit">{saving ? 'Saving...' : 'Save recurring rule'}</button></form></div>}
    {showCategory && <div className="modal-backdrop"><form className="modal" onSubmit={saveCategory}><div className="modal-heading"><h2>Add category</h2><button className="close-button" onClick={closeForms} type="button" aria-label="Close">×</button></div><label>Name<input required value={categoryName} onChange={event => setCategoryName(event.target.value)} /></label><label>Type<select value={categoryType} onChange={event => setCategoryType(event.target.value)}><option value="Income">Income</option><option value="Expense">Expense</option></select></label><button className="add-button full" disabled={saving} type="submit">{saving ? 'Saving...' : 'Save category'}</button></form></div>}
  </div>
}
export default App
