import { useEffect, useRef, useState } from 'react'
import type { FormEvent, MouseEvent as ReactMouseEvent } from 'react'
import './App.css'

type User = { id: number; name: string; role: 'Owner' | 'Member'; familyId: number }
type Account = { id: number; name: string; currency: string; openingBalance: number; active: boolean }
type Category = { id: number; name: string; type: 'Income' | 'Expense'; active: boolean }
type PlannedTransaction = { id: number; date: string; amount: number; fromAccountId: number | null; toAccountId: number | null; categoryId: number | null; recurringRuleId: number | null; goalId: number | null; description: string | null; cancelled: boolean; transactionType: 'INCOME' | 'EXPENSE' | 'TRANSFER' }
type RecurringRule = { id: number; name: string; amount: number; fromAccountId: number | null; toAccountId: number | null; categoryId: number | null; frequency: string; dayOfMonth: number | null; startDate: string; endDate: string | null; active: boolean; description: string | null; transactionType: 'INCOME' | 'EXPENSE' | 'TRANSFER' }
type Transaction = { id: number; date: string; amount: number; fromAccountId: number | null; toAccountId: number | null; categoryId: number | null; plannedTransactionId: number | null; goalId: number | null; description: string | null; transactionType: 'INCOME' | 'EXPENSE' | 'TRANSFER' }
type Goal = { id: number; name: string; targetAmount: number; targetDate: string; priority: 'Hard' | 'Soft'; recurringRuleId: number | null; description: string | null; active: boolean; currentFunding: number; remainingAmount: number; requiredMonthlyContribution: number; status: 'ACTIVE' | 'OVERDUE' | 'COMPLETE' }
type ForecastAccount = { accountId: number; name: string; currentBalance: number }
type ForecastEvent = { date: string; amount: number; fromAccountId: number | null; toAccountId: number | null; categoryId: number | null; goalId: number | null; transactionType: 'INCOME' | 'EXPENSE' | 'TRANSFER'; source: 'ACTUAL' | 'PLANNED' | 'RECURRING'; status: 'MATCHED' | 'PLANNED' | 'OVERDUE' | 'UNPLANNED'; plannedTransactionId: number | null; recurringRuleId: number | null; description: string | null }
type ForecastTrajectoryPoint = { date: string; accountBalances: Record<string, number>; totalBalance: number }
type Forecast = { planId: number; asOf: string; horizonEnd: string; accounts: ForecastAccount[]; events: ForecastEvent[]; trajectory: ForecastTrajectoryPoint[]; minimumFutureBalance: number; minimumFutureBalanceDate: string; negativeBalanceRisk: boolean }
type GoalFeasibility = { goalId: number; name: string; priority: 'Hard' | 'Soft'; status: 'FUNDED' | 'AT_RISK' }
type AvailableToSpend = { planId: number; asOf: string; horizonEnd: string; minimumReserve: number; forecastMinBalance: number; forecastMinBalanceDate: string; availableToSpend: number; reserveShortfall: number; planStatus: 'ON_TRACK' | 'AT_RISK'; goals: GoalFeasibility[] }
type FamilyInfo = { id: number; name: string; defaultMinimumReserve: number }
type PlanInfo = { id: number; name: string; description: string | null; isDefault: boolean; isActive: boolean; minimumReserve: number | null }
type CategoryCompliance = { categoryId: number; categoryName: string; categoryType: 'Income' | 'Expense'; plannedAmount: number; actualAmount: number; variance: number; variancePercent: number | null; favorability: 'FAVORABLE' | 'UNFAVORABLE' | 'ON_PLAN'; plannedRealCount: number; plannedRecurringCount: number; actualMatchedCount: number; actualUnmatchedCount: number; averageTimingVarianceDays: number | null }
type GoalCompliance = { goalId: number; goalName: string; priority: 'Hard' | 'Soft'; plannedContribution: number; actualContribution: number; variance: number; variancePercent: number | null; favorability: 'FAVORABLE' | 'UNFAVORABLE' | 'ON_PLAN' }
type ComplianceTotals = { plannedIncome: number; actualIncome: number; incomeVariance: number; plannedExpense: number; actualExpense: number; expenseVariance: number; netVariance: number; categoriesOnPlanRatio: number | null }
type PeriodCompliance = { periodStart: string; periodEnd: string; status: 'CLOSED' | 'IN_PROGRESS' | 'FUTURE'; categories: CategoryCompliance[]; goals: GoalCompliance[]; totals: ComplianceTotals }
type PlanCompliance = { planId: number; asOf: string; from: string; to: string; periods: PeriodCompliance[]; totals: ComplianceTotals }
type Form = { fromAccountId: string; toAccountId: string; categoryId: string; goalId: string; recurringRuleId: string; plannedTransactionId: string; description: string; amount: string; date: string }
type PlannedForm = Form
type RecurringForm = { name: string; amount: string; fromAccountId: string; toAccountId: string; categoryId: string; frequency: string; dayOfMonth: string; startDate: string; endDate: string; description: string }
type GoalForm = { name: string; targetAmount: string; targetDate: string; priority: 'Hard' | 'Soft'; recurringRuleId: string; description: string }
const API_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:5140/api'
const emptyForm: Form = { fromAccountId: '', toAccountId: '', categoryId: '', goalId: '', recurringRuleId: '', plannedTransactionId: '', description: '', amount: '', date: new Date().toISOString().slice(0, 10) }
const emptyGoalForm: GoalForm = { name: '', targetAmount: '', targetDate: new Date().toISOString().slice(0, 10), priority: 'Soft', recurringRuleId: '', description: '' }
let activeUserId = localStorage.getItem('finplanner:userId') ?? ''

function periodBounds(period: string) { const [year, month] = period.split('-').map(Number); const lastDay = new Date(year, month, 0).getDate(); return { from: `${period}-01`, to: `${period}-${String(lastDay).padStart(2, '0')}` } }
function shiftPeriod(period: string, offset: number) { const [year, month] = period.split('-').map(Number); const absolute = year * 12 + month - 1 + offset; return `${Math.floor(absolute / 12)}-${String((absolute % 12) + 1).padStart(2, '0')}` }
async function request<T>(path: string, options?: RequestInit): Promise<T> { const headers: Record<string, string> = { 'Content-Type': 'application/json' }; if (activeUserId) headers['X-User-Id'] = activeUserId; const response = await fetch(`${API_URL}${path}`, { headers, ...options }); if (!response.ok) throw new Error(await response.text() || `Request failed (${response.status})`); return response.status === 204 ? undefined as T : response.json() }

function monthLabel(date: Date) { return `${String(date.getUTCMonth() + 1).padStart(2, '0')}/${String(date.getUTCFullYear()).slice(2)}` }
function dayLabel(date: Date) { return `${String(date.getUTCDate()).padStart(2, '0')}/${String(date.getUTCMonth() + 1).padStart(2, '0')}/${String(date.getUTCFullYear()).slice(2)}` }

function ForecastChart({ asOf, horizonEnd, trajectory, minimumDate, currentBalance, money }: { asOf: string; horizonEnd: string; trajectory: ForecastTrajectoryPoint[]; minimumDate: string; currentBalance: number; money: Intl.NumberFormat }) {
  const svgRef = useRef<SVGSVGElement>(null)
  const [hover, setHover] = useState<{ x: number; label: string; value: number } | null>(null)
  const width = 680, height = 170, padLeft = 64, padRight = 12, padTop = 14, padBottom = 26
  const innerWidth = width - padLeft - padRight, innerHeight = height - padTop - padBottom

  const asOfTime = new Date(asOf).getTime(), horizonTime = new Date(horizonEnd).getTime()
  const totalSpan = horizonTime - asOfTime || 1

  const series: { date: string; totalBalance: number }[] = []
  if (!trajectory.length || trajectory[0].date !== asOf) series.push({ date: asOf, totalBalance: currentBalance })
  series.push(...trajectory.map(point => ({ date: point.date, totalBalance: point.totalBalance })))
  if (series[series.length - 1].date !== horizonEnd) series.push({ date: horizonEnd, totalBalance: series[series.length - 1].totalBalance })

  const values = series.map(point => point.totalBalance)
  const min = Math.min(0, ...values), max = Math.max(...values, 1)
  const range = max - min || 1

  const xFor = (dateStr: string) => padLeft + (new Date(dateStr).getTime() - asOfTime) / totalSpan * innerWidth
  const yFor = (value: number) => padTop + innerHeight - (value - min) / range * innerHeight
  const valueAt = (timeMs: number) => { let value = series[0].totalBalance; for (const point of series) { if (new Date(point.date).getTime() <= timeMs) value = point.totalBalance; else break }; return value }

  // Step-after path (flat, then a vertical jump at each event date) — matches the underlying
  // forecast semantics exactly (balance is constant between events, never interpolated), and keeps
  // the hover dot (also computed via step semantics below) exactly on the drawn line.
  const pathD = series.reduce((acc, point, index) => {
    const x = xFor(point.date), y = yFor(point.totalBalance)
    return index === 0 ? `M ${x},${y}` : `${acc} H ${x} V ${y}`
  }, '')
  const minIndex = series.findIndex(point => point.date === minimumDate)

  const months: { x: number; label: string }[] = []
  const cursor = new Date(asOf); cursor.setUTCDate(1)
  const horizon = new Date(horizonEnd)
  while (cursor <= horizon) {
    months.push({ x: padLeft + Math.max(0, cursor.getTime() - asOfTime) / totalSpan * innerWidth, label: monthLabel(cursor) })
    cursor.setUTCMonth(cursor.getUTCMonth() + 1)
  }
  const monthSkip = Math.max(1, Math.ceil(months.length / 8))
  const yTicks = [min, min + range / 2, max]

  const handleMove = (event: ReactMouseEvent<SVGSVGElement>) => {
    const rect = svgRef.current?.getBoundingClientRect()
    if (!rect || !rect.width) return
    const relativeX = (event.clientX - rect.left) / rect.width * width
    const clampedX = Math.min(Math.max(relativeX, padLeft), width - padRight)
    const timeMs = asOfTime + (clampedX - padLeft) / innerWidth * totalSpan
    setHover({ x: clampedX, label: dayLabel(new Date(timeMs)), value: valueAt(timeMs) })
  }

  return <div className="forecast-chart-wrap">
    <svg ref={svgRef} className="forecast-chart" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" onMouseMove={handleMove} onMouseLeave={() => setHover(null)}>
      {yTicks.map((tick, index) => <g key={index}>
        <line x1={padLeft} y1={yFor(tick)} x2={width - padRight} y2={yFor(tick)} className="forecast-chart-gridline" />
        <text x={padLeft - 6} y={yFor(tick)} className="forecast-chart-axis-label" textAnchor="end" dominantBaseline="middle">{money.format(tick)}</text>
      </g>)}
      {months.map((month, index) => index % monthSkip === 0 && <g key={month.label + index}>
        <line x1={month.x} y1={padTop} x2={month.x} y2={height - padBottom} className="forecast-chart-gridline" />
        <text x={month.x} y={height - padBottom + 14} className="forecast-chart-axis-label" textAnchor="middle">{month.label}</text>
      </g>)}
      <line x1={padLeft} y1={yFor(0)} x2={width - padRight} y2={yFor(0)} className="forecast-chart-zero" />
      <path d={pathD} className="forecast-chart-line" />
      {minIndex >= 0 && <circle cx={xFor(series[minIndex].date)} cy={yFor(series[minIndex].totalBalance)} r="4" className="forecast-chart-min" />}
      {hover && <><line x1={hover.x} y1={padTop} x2={hover.x} y2={height - padBottom} className="forecast-chart-hover-line" /><circle cx={hover.x} cy={yFor(hover.value)} r="4" className="forecast-chart-hover-dot" /></>}
    </svg>
    {hover && <div className="forecast-chart-tooltip" style={{ left: `${hover.x / width * 100}%`, top: `${yFor(hover.value) / height * 100}%` }}><strong>{hover.label}</strong><span>{money.format(hover.value)}</span></div>}
  </div>
}

function App() {
  const [users, setUsers] = useState<User[]>([]); const [userId, setUserId] = useState(activeUserId)
  const [accounts, setAccounts] = useState<Account[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [planned, setPlanned] = useState<PlannedTransaction[]>([]); const [recurring, setRecurring] = useState<RecurringRule[]>([]); const [goals, setGoals] = useState<Goal[]>([]); const [forecast, setForecast] = useState<Forecast | null>(null); const [forecastLoading, setForecastLoading] = useState(false); const [ats, setAts] = useState<AvailableToSpend | null>(null); const [familyInfo, setFamilyInfo] = useState<FamilyInfo | null>(null); const [reserveInput, setReserveInput] = useState(''); const [familyReserveInput, setFamilyReserveInput] = useState(''); const [activeView, setActiveView] = useState('Transactions');
  const [compliance, setCompliance] = useState<PlanCompliance | null>(null); const [complianceLoading, setComplianceLoading] = useState(false); const [complianceMonths, setComplianceMonths] = useState(12); const [complianceSelectedPeriod, setComplianceSelectedPeriod] = useState('');
  const [period, setPeriod] = useState(() => new Date().toISOString().slice(0, 7)); const [filter, setFilter] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [showTransaction, setShowTransaction] = useState(false); const [showAccount, setShowAccount] = useState(false); const [editingId, setEditingId] = useState<number | null>(null); const [editingAccountId, setEditingAccountId] = useState<number | null>(null); const [form, setForm] = useState<Form>(emptyForm); const [accountName, setAccountName] = useState(''); const [currency, setCurrency] = useState('EUR'); const [openingBalance, setOpeningBalance] = useState('0'); const [saving, setSaving] = useState(false)
  const [showPlanned, setShowPlanned] = useState(false); const [showRecurring, setShowRecurring] = useState(false); const [showCategory, setShowCategory] = useState(false); const [showGoal, setShowGoal] = useState(false); const [editingPlannedId, setEditingPlannedId] = useState<number | null>(null); const [editingGoalId, setEditingGoalId] = useState<number | null>(null); const [editingRecurringId, setEditingRecurringId] = useState<number | null>(null); const [plannedForm, setPlannedForm] = useState<PlannedForm>(emptyForm); const [recurringForm, setRecurringForm] = useState<RecurringForm>({ name: '', amount: '', fromAccountId: '', toAccountId: '', categoryId: '', frequency: 'Monthly', dayOfMonth: '', startDate: new Date().toISOString().slice(0, 10), endDate: '', description: '' }); const [goalForm, setGoalForm] = useState<GoalForm>(emptyGoalForm); const [categoryName, setCategoryName] = useState(''); const [categoryType, setCategoryType] = useState('Expense')
  useEffect(() => { request<User[]>('/users').then(setUsers).catch(() => {}) }, [])
  useEffect(() => { if (!userId && users.length) setUserId(String(users[0].id)) }, [users, userId])
  useEffect(() => { activeUserId = userId; if (userId) localStorage.setItem('finplanner:userId', userId); else localStorage.removeItem('finplanner:userId') }, [userId])
  const selectedUser = users.find(user => String(user.id) === userId)
  const loadData = async () => { if (!userId) return; setLoading(true); setError(''); try { const [loadedAccounts, loadedCategories, loadedTransactions, loadedPlanned, loadedRecurring, loadedGoals] = await Promise.all([request<Account[]>(`/accounts?includeInactive=${activeView === 'Accounts'}`), request<Category[]>('/categories'), request<Transaction[]>(`/transactions?from=${periodBounds(period).from}&to=${periodBounds(period).to}${filter ? `&type=${filter}` : ''}`), request<PlannedTransaction[]>(`/planning/planned-transactions?from=${periodBounds(period).from}&to=${periodBounds(period).to}${filter ? `&type=${filter}` : ''}`), request<RecurringRule[]>('/planning/recurring-rules'), request<Goal[]>('/goals')]); setAccounts(loadedAccounts); setCategories(loadedCategories); setTransactions(loadedTransactions); setPlanned(loadedPlanned); setRecurring(loadedRecurring); setGoals(loadedGoals) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load data.') } finally { setLoading(false) } }
  useEffect(() => { void loadData() }, [period, filter, activeView, userId])
  const loadForecastTab = async () => { setForecastLoading(true); try { const [loadedForecast, loadedAts, loadedFamily, loadedPlans] = await Promise.all([request<Forecast>('/planning/forecast?horizonMonths=12'), request<AvailableToSpend>('/planning/available-to-spend?horizonMonths=12'), request<FamilyInfo>('/family'), request<PlanInfo[]>('/plans')]); setForecast(loadedForecast); setAts(loadedAts); setFamilyInfo(loadedFamily); setFamilyReserveInput(String(loadedFamily.defaultMinimumReserve)); const currentPlan = loadedPlans.find(plan => plan.id === loadedAts.planId); setReserveInput(currentPlan?.minimumReserve != null ? String(currentPlan.minimumReserve) : '') } catch (e) { setError(e instanceof Error ? e.message : 'Could not load forecast.') } finally { setForecastLoading(false) } }
  useEffect(() => { if (activeView !== 'Forecast' || !userId) return; void loadForecastTab() }, [activeView, userId])
  const saveReserve = async () => { if (!ats) return; try { await request(`/plans/${ats.planId}/reserve`, { method: 'PUT', body: JSON.stringify({ minimumReserve: reserveInput ? Number(reserveInput) : null }) }); await loadForecastTab() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save plan reserve.') } }
  const saveFamilyReserve = async () => { try { await request('/family', { method: 'PUT', body: JSON.stringify({ defaultMinimumReserve: Number(familyReserveInput || '0') }) }); await loadForecastTab() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save family default reserve.') } }
  const complianceRangeFrom = (months: number) => { const d = new Date(); d.setDate(1); d.setMonth(d.getMonth() - (months - 1)); return d.toISOString().slice(0, 10) }
  const loadComplianceTab = async () => { setComplianceLoading(true); try { const loaded = await request<PlanCompliance>(`/planning/compliance?from=${complianceRangeFrom(complianceMonths)}&to=${new Date().toISOString().slice(0, 10)}`); setCompliance(loaded); setComplianceSelectedPeriod(current => loaded.periods.find(period => period.periodStart === current) ? current : (loaded.periods[loaded.periods.length - 1]?.periodStart ?? '')) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load compliance report.') } finally { setComplianceLoading(false) } }
  useEffect(() => { if (activeView !== 'Compliance' || !userId) return; void loadComplianceTab() }, [activeView, userId, complianceMonths])
  const favorabilityFor = (type: 'Income' | 'Expense', variance: number): 'FAVORABLE' | 'UNFAVORABLE' | 'ON_PLAN' => variance === 0 ? 'ON_PLAN' : type === 'Income' ? (variance > 0 ? 'FAVORABLE' : 'UNFAVORABLE') : (variance > 0 ? 'UNFAVORABLE' : 'FAVORABLE')
  const categoryTotals = compliance ? Object.values(compliance.periods.flatMap(period => period.categories).reduce((acc, item) => { const existing = acc[item.categoryId] ?? { categoryId: item.categoryId, categoryName: item.categoryName, categoryType: item.categoryType, plannedAmount: 0, actualAmount: 0, variance: 0 }; existing.plannedAmount += item.plannedAmount; existing.actualAmount += item.actualAmount; existing.variance += item.variance; acc[item.categoryId] = existing; return acc }, {} as Record<number, { categoryId: number; categoryName: string; categoryType: 'Income' | 'Expense'; plannedAmount: number; actualAmount: number; variance: number }>)) : []
  const topDivergences = [...categoryTotals].sort((a, b) => Math.abs(b.variance) - Math.abs(a.variance)).slice(0, 6)
  const selectedCompliancePeriod = compliance?.periods.find(period => period.periodStart === complianceSelectedPeriod) ?? null
  const money = new Intl.NumberFormat('en-IE', { style: 'currency', currency: accounts[0]?.currency ?? 'EUR' }); const accountNameFor = (id: number | null) => accounts.find(account => account.id === id)?.name ?? 'External account'
  const openNewTransaction = () => { setEditingId(null); setForm({ ...emptyForm, toAccountId: accounts[0] ? String(accounts[0].id) : '' }); setShowTransaction(true) }
  const openEditTransaction = (item: Transaction) => { setEditingId(item.id); setForm({ fromAccountId: String(item.fromAccountId ?? ''), toAccountId: String(item.toAccountId ?? ''), categoryId: String(item.categoryId ?? ''), goalId: String(item.goalId ?? ''), recurringRuleId: '', plannedTransactionId: String(item.plannedTransactionId ?? ''), description: item.description ?? '', amount: String(item.amount), date: item.date }); setShowTransaction(true) }
  const saveTransaction = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await request(`/transactions${editingId ? `/${editingId}` : ''}`, { method: editingId ? 'PUT' : 'POST', body: JSON.stringify({ date: form.date, amount: Number(form.amount), fromAccountId: form.fromAccountId ? Number(form.fromAccountId) : null, toAccountId: form.toAccountId ? Number(form.toAccountId) : null, categoryId: form.categoryId ? Number(form.categoryId) : null, goalId: form.goalId ? Number(form.goalId) : null, plannedTransactionId: form.plannedTransactionId ? Number(form.plannedTransactionId) : null, description: form.description || null }) }); setShowTransaction(false); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save transaction.') } finally { setSaving(false) } }
  const deleteTransaction = async (item: Transaction) => { if (!window.confirm(`Delete “${item.description ?? 'transaction'}”?`)) return; try { await request(`/transactions/${item.id}`, { method: 'DELETE' }); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not delete transaction.') } }
  const saveAccount = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const path = editingAccountId ? `/accounts/${editingAccountId}` : '/accounts'; const method = editingAccountId ? 'PUT' : 'POST'; await request(path, { method, body: JSON.stringify(editingAccountId ? { name: accountName, currency, openingBalance: Number(openingBalance), active: true } : { name: accountName, currency, openingBalance: Number(openingBalance) }) }); setShowAccount(false); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save account.') } finally { setSaving(false) } }
  const openNewAccount = () => { setEditingAccountId(null); setAccountName(''); setCurrency('EUR'); setOpeningBalance('0'); setShowAccount(true) }; const openEditAccount = (account: Account) => { setEditingAccountId(account.id); setAccountName(account.name); setCurrency(account.currency); setOpeningBalance(String(account.openingBalance)); setShowAccount(true) }
  const deactivate = async (account: Account) => { if (!window.confirm(`Deactivate “${account.name}”?`)) return; await request(`/accounts/${account.id}`, { method: 'DELETE' }); await loadData() }
  const closeForms = () => { if (!saving) { setShowTransaction(false); setShowAccount(false); setShowPlanned(false); setShowRecurring(false); setShowCategory(false); setShowGoal(false) } }
  useEffect(() => {
    document.querySelectorAll<HTMLFormElement>('form.modal').forEach(modal => {
      if (modal.querySelector('.modal-inline-close') || modal.querySelector('.close-button')) return
      const closeButton = document.createElement('button')
      closeButton.className = 'close-button modal-inline-close'
      closeButton.type = 'button'
      closeButton.setAttribute('aria-label', 'Close')
      closeButton.textContent = '×'
      closeButton.addEventListener('click', closeForms)
      const title = modal.querySelector(':scope > h2')
      const heading = document.createElement('div')
      heading.className = 'modal-heading'
      if (title) heading.appendChild(title)
      heading.appendChild(closeButton)
      modal.prepend(heading)
    })
  }, [showTransaction, showAccount])
  const openNewPlanned = () => { setEditingPlannedId(null); setPlannedForm({ ...emptyForm, toAccountId: accounts[0] ? String(accounts[0].id) : '' }); setShowPlanned(true) }
  const openEditPlanned = (item: PlannedTransaction) => { setEditingPlannedId(item.id); setPlannedForm({ fromAccountId: String(item.fromAccountId ?? ''), toAccountId: String(item.toAccountId ?? ''), categoryId: String(item.categoryId ?? ''), goalId: String(item.goalId ?? ''), recurringRuleId: String(item.recurringRuleId ?? ''), plannedTransactionId: '', description: item.description ?? '', amount: String(item.amount), date: item.date }); setShowPlanned(true) }
  const savePlanned = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const body = { date: plannedForm.date, amount: Number(plannedForm.amount), fromAccountId: plannedForm.fromAccountId ? Number(plannedForm.fromAccountId) : null, toAccountId: plannedForm.toAccountId ? Number(plannedForm.toAccountId) : null, categoryId: plannedForm.categoryId ? Number(plannedForm.categoryId) : null, goalId: plannedForm.goalId ? Number(plannedForm.goalId) : null, description: plannedForm.description || null }; await request(`/planning/planned-transactions${editingPlannedId ? `/${editingPlannedId}` : ''}`, { method: editingPlannedId ? 'PUT' : 'POST', body: JSON.stringify(editingPlannedId ? body : { ...body, recurringRuleId: plannedForm.recurringRuleId ? Number(plannedForm.recurringRuleId) : null }) }); setShowPlanned(false); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save planned transaction.') } finally { setSaving(false) } }
  const deletePlanned = async (item: PlannedTransaction) => { if (!window.confirm(`Delete “${item.description ?? 'planned transaction'}”?`)) return; try { await request(`/planning/planned-transactions/${item.id}`, { method: 'DELETE' }); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not delete planned transaction.') } }
  const materializeOccurrence = (occurrence: ForecastEvent) => { setEditingPlannedId(null); setPlannedForm({ fromAccountId: String(occurrence.fromAccountId ?? ''), toAccountId: String(occurrence.toAccountId ?? ''), categoryId: String(occurrence.categoryId ?? ''), goalId: String(occurrence.goalId ?? ''), recurringRuleId: String(occurrence.recurringRuleId ?? ''), plannedTransactionId: '', description: occurrence.description ?? '', amount: String(occurrence.amount), date: occurrence.date }); setShowPlanned(true) }
  const openNewRecurring = () => { setEditingRecurringId(null); setRecurringForm({ name: '', amount: '', fromAccountId: '', toAccountId: '', categoryId: '', frequency: 'Monthly', dayOfMonth: '', startDate: new Date().toISOString().slice(0, 10), endDate: '', description: '' }); setShowRecurring(true) }
  const openEditRecurring = (item: RecurringRule) => { setEditingRecurringId(item.id); setRecurringForm({ name: item.name, amount: String(item.amount), fromAccountId: String(item.fromAccountId ?? ''), toAccountId: String(item.toAccountId ?? ''), categoryId: String(item.categoryId ?? ''), frequency: item.frequency, dayOfMonth: String(item.dayOfMonth ?? ''), startDate: item.startDate, endDate: item.endDate ?? '', description: item.description ?? '' }); setShowRecurring(true) }
  const saveRecurring = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const body = { name: recurringForm.name, amount: Number(recurringForm.amount), fromAccountId: recurringForm.fromAccountId ? Number(recurringForm.fromAccountId) : null, toAccountId: recurringForm.toAccountId ? Number(recurringForm.toAccountId) : null, categoryId: recurringForm.categoryId ? Number(recurringForm.categoryId) : null, frequency: recurringForm.frequency, dayOfMonth: recurringForm.dayOfMonth ? Number(recurringForm.dayOfMonth) : null, startDate: recurringForm.startDate, endDate: recurringForm.endDate || null, description: recurringForm.description || null }; await request(`/planning/recurring-rules${editingRecurringId ? `/${editingRecurringId}` : ''}`, { method: editingRecurringId ? 'PUT' : 'POST', body: JSON.stringify(body) }); setShowRecurring(false); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save recurring rule.') } finally { setSaving(false) } }
  const deactivateRecurring = async (item: RecurringRule) => { if (!window.confirm(`Deactivate “${item.name}”?`)) return; try { await request(`/planning/recurring-rules/${item.id}`, { method: 'DELETE' }); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not deactivate recurring rule.') } }
  const saveCategory = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await request('/categories', { method: 'POST', body: JSON.stringify({ name: categoryName, type: categoryType }) }); setCategoryName(''); setShowCategory(false); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save category.') } finally { setSaving(false) } }
  const openNewGoal = () => { setEditingGoalId(null); setGoalForm(emptyGoalForm); setShowGoal(true) }
  const openEditGoal = (goal: Goal) => { setEditingGoalId(goal.id); setGoalForm({ name: goal.name, targetAmount: String(goal.targetAmount), targetDate: goal.targetDate, priority: goal.priority, recurringRuleId: String(goal.recurringRuleId ?? ''), description: goal.description ?? '' }); setShowGoal(true) }
  const saveGoal = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const body = { name: goalForm.name, targetAmount: Number(goalForm.targetAmount), targetDate: goalForm.targetDate, priority: goalForm.priority, recurringRuleId: goalForm.recurringRuleId ? Number(goalForm.recurringRuleId) : null, description: goalForm.description || null }; await request(`/goals${editingGoalId ? `/${editingGoalId}` : ''}`, { method: editingGoalId ? 'PUT' : 'POST', body: JSON.stringify(body) }); setShowGoal(false); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save goal.') } finally { setSaving(false) } }
  const deactivateGoal = async (goal: Goal) => { if (!window.confirm(`Deactivate “${goal.name}”?`)) return; try { await request(`/goals/${goal.id}`, { method: 'DELETE' }); await loadData() } catch (e) { setError(e instanceof Error ? e.message : 'Could not deactivate goal.') } }
  const income = transactions.filter(item => item.transactionType === 'INCOME').reduce((sum, item) => sum + item.amount, 0); const expense = transactions.filter(item => item.transactionType === 'EXPENSE').reduce((sum, item) => sum + item.amount, 0)
  const plannedIncome = planned.filter(item => item.transactionType === 'INCOME').reduce((sum, item) => sum + item.amount, 0); const plannedExpense = planned.filter(item => item.transactionType === 'EXPENSE').reduce((sum, item) => sum + item.amount, 0)

  return <div className={`app-shell ${activeView.toLowerCase()}`}>{(showTransaction || showAccount) && <button className="modal-global-close" onClick={closeForms} type="button" aria-label="Close form">×</button>}
    <aside className="sidebar"><div className="brand"><span className="brand-mark">F</span><span>finplanner</span></div>
      <label className="family-switcher" htmlFor="active-user"><span className="avatar">{(selectedUser?.name ?? '?')[0]}</span><span><strong>{selectedUser?.name ?? 'Select user'}</strong><small>{selectedUser?.role ?? 'No user selected'}</small></span><select id="active-user" aria-label="Active user" value={userId} onChange={event => setUserId(event.target.value)}><option value="" disabled>Select user</option>{users.map(user => <option value={user.id} key={user.id}>{user.name}</option>)}</select></label>
      <nav aria-label="Main navigation">{['Transactions', 'Planned', 'Recurring', 'Goals', 'Forecast', 'Compliance', 'Categories', 'Accounts'].map(item => <button className={activeView === item ? 'nav-item active' : 'nav-item'} key={item} onClick={() => setActiveView(item)} type="button"><span className="nav-icon">{item === 'Transactions' ? '↕' : item === 'Planned' ? '◷' : item === 'Recurring' ? '↻' : item === 'Goals' ? '★' : item === 'Forecast' ? '⟶' : item === 'Compliance' ? '✓' : item === 'Categories' ? '◉' : '◫'}</span>{item}</button>)}</nav></aside>
    <main className="main-content"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> {activeView}</div>{activeView === 'Accounts' && <button className="add-button" onClick={openNewAccount} type="button"><span>+</span> Add account</button>}{activeView === 'Transactions' && <button className="add-button" onClick={openNewTransaction} type="button"><span>+</span> Add transaction</button>}{activeView === 'Planned' && <button className="add-button" onClick={openNewPlanned} type="button"><span>+</span> Add planned</button>}{activeView === 'Recurring' && <button className="add-button" onClick={openNewRecurring} type="button"><span>+</span> Add recurring rule</button>}{activeView === 'Goals' && <button className="add-button" onClick={openNewGoal} type="button"><span>+</span> Add goal</button>}{activeView === 'Categories' && <button className="add-button" onClick={() => setShowCategory(true)} type="button"><span>+</span> Add category</button>}</header>
      <div className="content-wrap"><section className="page-heading"><div><p className="eyebrow">Household activity</p><h1>{activeView}</h1><p className="muted">{activeView === 'Accounts' ? 'Manage accounts from the final database model.' : 'Actual transactions from your planned and unplanned activity.'}</p></div>{(activeView === 'Transactions' || activeView === 'Planned') && <div className="period-controls"><button className="month-arrow" onClick={() => setPeriod(current => shiftPeriod(current, -1))} aria-label="Previous month" type="button">‹</button><input aria-label="Month" type="month" value={period} onChange={event => setPeriod(event.target.value)} /><button className="month-arrow" onClick={() => setPeriod(current => shiftPeriod(current, 1))} aria-label="Next month" type="button">›</button><select aria-label="Transaction type" value={filter} onChange={event => setFilter(event.target.value)}><option value="">All types</option><option value="Income">Income</option><option value="Expense">Expenses</option></select></div>}</section>
        {error && <div className="error-banner" role="alert">{error}</div>}
        {activeView === 'Transactions' ? <><section className="metric-grid"><article className="metric-card"><div className="metric-top"><span>Income</span></div><strong>{money.format(income)}</strong></article><article className="metric-card"><div className="metric-top"><span>Expenses</span></div><strong>{money.format(expense)}</strong></article><article className="metric-card"><div className="metric-top"><span>Net</span></div><strong>{money.format(income - expense)}</strong></article><article className="metric-card"><div className="metric-top"><span>Actual transactions</span></div><strong>{transactions.length}</strong></article></section><section className="panel transaction-panel"><div className="panel-heading"><div><h2>Actual transactions</h2><p className="muted">{period} · {transactions.length} records</p></div></div>{loading ? <p className="empty-state">Loading...</p> : !transactions.length ? <div className="empty-state"><strong>No actual transactions</strong><button className="add-button" onClick={openNewTransaction} type="button">+ Add transaction</button></div> : <div className="transaction-list">{transactions.map(item => <div className="transaction" key={item.id}><span className="transaction-icon green">{item.transactionType[0]}</span><span className="transaction-info"><strong>{item.description ?? 'No description'}</strong><small>{item.transactionType} · {accountNameFor(item.fromAccountId)} → {accountNameFor(item.toAccountId)} · {item.date}</small></span><strong className={item.transactionType === 'INCOME' ? 'amount income-amount' : 'amount'}>{item.transactionType === 'EXPENSE' ? '-' : '+'}{money.format(item.amount)}</strong><button className="row-action" onClick={() => openEditTransaction(item)} type="button" aria-label="Edit transaction">✎</button><button className="row-action danger" onClick={() => void deleteTransaction(item)} type="button" aria-label="Delete transaction">×</button></div>)}</div>}</section></> : <section className="panel account-panel"><div className="panel-heading"><div><h2>Accounts</h2><p className="muted">{accounts.length} accounts</p></div><button className="link-button" onClick={openNewAccount} type="button">Add account +</button></div>{accounts.map(account => <div className="account-row" key={account.id}><span className="account-badge">{account.name[0]}</span><span className="transaction-info"><strong>{account.name}</strong><small>{account.currency} · opening {money.format(account.openingBalance)} · {account.active ? 'Active' : 'Inactive'}</small></span><button className="row-action" onClick={() => openEditAccount(account)} type="button">✎</button>{account.active && <button className="row-action danger" onClick={() => void deactivate(account)} type="button">×</button>}</div>)}</section>}
        <section className={`panel model-panel planned-panel ${activeView === 'Planned' ? 'visible-panel' : ''}`}><div className="metric-grid plan-metric-grid"><article className="metric-card"><div className="metric-top"><span>Income</span></div><strong>{money.format(plannedIncome)}</strong></article><article className="metric-card"><div className="metric-top"><span>Expenses</span></div><strong>{money.format(plannedExpense)}</strong></article><article className="metric-card"><div className="metric-top"><span>Net</span></div><strong>{money.format(plannedIncome - plannedExpense)}</strong></article><article className="metric-card"><div className="metric-top"><span>Planned transactions</span></div><strong>{planned.length}</strong></article></div><div className="panel-heading"><div><h2>Planned transactions</h2><p className="muted">{planned.length} planned items for {period}</p></div></div>{planned.length ? <div className="transaction-list">{planned.map(item => <div className="transaction" key={item.id}><span className="transaction-icon yellow">P</span><span className="transaction-info"><strong>{item.description ?? 'Planned transaction'}</strong><small>{item.date} · {item.cancelled ? 'Cancelled' : item.recurringRuleId ? 'Recurring' : 'One-time'}</small></span><strong className={item.transactionType === 'INCOME' ? 'amount income-amount' : 'amount'}>{money.format(item.amount)}</strong><button className="row-action" onClick={() => openEditPlanned(item)} type="button" aria-label="Edit planned transaction">✎</button><button className="row-action danger" onClick={() => void deletePlanned(item)} type="button" aria-label="Delete planned transaction">×</button></div>)}</div> : <p className="empty-state">No planned transactions for this month.</p>}</section>
        <section className={`panel model-panel recurring-panel ${activeView === 'Recurring' ? 'visible-panel' : ''}`}><div className="panel-heading"><div><h2>Recurring rules</h2><p className="muted">{recurring.length} rules</p></div></div>{recurring.length ? <div className="transaction-list">{recurring.map(item => <div className="transaction" key={item.id}><span className={`transaction-icon ${item.transactionType === 'INCOME' ? 'green' : item.transactionType === 'TRANSFER' ? 'purple' : 'blue'}`}>↻</span><span className="transaction-info"><strong>{item.name}</strong><small>{item.frequency} · from {item.startDate}{item.endDate ? ` to ${item.endDate}` : ''} · {item.active ? 'Active' : 'Inactive'}</small></span><strong className={item.transactionType === 'INCOME' ? 'amount income-amount' : 'amount'}>{money.format(item.amount)}</strong><button className="row-action" onClick={() => openEditRecurring(item)} type="button" aria-label="Edit recurring rule">✎</button>{item.active && <button className="row-action danger" onClick={() => void deactivateRecurring(item)} type="button" aria-label="Deactivate recurring rule">×</button>}</div>)}</div> : <p className="empty-state">No recurring rules configured.</p>}</section>
        <section className={`panel model-panel goals-panel ${activeView === 'Goals' ? 'visible-panel' : ''}`}><div className="panel-heading"><div><h2>Goals</h2><p className="muted">{goals.length} goals</p></div></div>{goals.length ? <div className="transaction-list">{goals.map(goal => { const pct = goal.targetAmount > 0 ? Math.min(100, Math.round(goal.currentFunding / goal.targetAmount * 100)) : 0; return <div className="transaction" key={goal.id}><span className={`transaction-icon ${goal.priority === 'Hard' ? 'blue' : 'yellow'}`}>{goal.priority[0]}</span><span className="transaction-info"><strong>{goal.name}</strong><small>{money.format(goal.currentFunding)} / {money.format(goal.targetAmount)} · due {goal.targetDate} · {goal.priority} · <span className={`pill pill-${goal.status.toLowerCase()}`}>{goal.status}</span>{!goal.active && ' · Inactive'}</small><div className="budget-track goal-progress"><i style={{ width: `${pct}%` }}></i></div></span><button className="row-action" onClick={() => openEditGoal(goal)} type="button" aria-label="Edit goal">✎</button>{goal.active && <button className="row-action danger" onClick={() => void deactivateGoal(goal)} type="button" aria-label="Deactivate goal">×</button>}</div> })}</div> : <p className="empty-state">No goals configured.</p>}</section>
        <section className={`panel model-panel forecast-panel ${activeView === 'Forecast' ? 'visible-panel' : ''}`}><div className="panel-heading"><div><h2>Forecast</h2><p className="muted">{forecast ? `${forecast.asOf} → ${forecast.horizonEnd}` : '12-month cash-flow projection'}</p></div></div>{forecastLoading ? <p className="empty-state">Loading...</p> : !forecast || !ats ? <p className="empty-state">No forecast available.</p> : <>
          <section className="metric-grid"><article className="metric-card"><div className="metric-top"><span>Available to spend</span></div><strong>{money.format(ats.availableToSpend)}</strong></article><article className="metric-card"><div className="metric-top"><span>Minimum reserve</span></div><strong>{money.format(ats.minimumReserve)}</strong></article><article className="metric-card"><div className="metric-top"><span>Plan status</span></div><strong className={ats.planStatus === 'AT_RISK' ? 'negative' : ''}>{ats.planStatus}</strong></article><article className="metric-card"><div className="metric-top"><span>Reserve shortfall</span></div><strong>{money.format(ats.reserveShortfall)}</strong></article></section>
          <div className="form-row reserve-row"><label>Plan reserve override<input type="number" min="0" step="0.01" placeholder={`family default: ${familyInfo ? money.format(familyInfo.defaultMinimumReserve) : ''}`} value={reserveInput} onChange={event => setReserveInput(event.target.value)} /></label><button className="add-button" onClick={() => void saveReserve()} type="button">Save plan reserve</button><label>Family default reserve<input type="number" min="0" step="0.01" value={familyReserveInput} onChange={event => setFamilyReserveInput(event.target.value)} /></label><button className="add-button" onClick={() => void saveFamilyReserve()} type="button">Save family default</button></div>
          {ats.goals.length > 0 && <div className="transaction-list goal-feasibility-list">{ats.goals.map(goal => <div className="transaction" key={goal.goalId}><span className={`transaction-icon ${goal.priority === 'Hard' ? 'blue' : 'yellow'}`}>{goal.priority[0]}</span><span className="transaction-info"><strong>{goal.name}</strong><small>{goal.priority}</small></span><span className={`pill pill-${goal.status.toLowerCase()}`}>{goal.status}</span></div>)}</div>}
          <section className="metric-grid"><article className="metric-card"><div className="metric-top"><span>Minimum projected balance</span></div><strong>{money.format(forecast.minimumFutureBalance)}</strong><p className={forecast.negativeBalanceRisk ? 'negative' : ''}>{forecast.minimumFutureBalanceDate}</p></article><article className="metric-card"><div className="metric-top"><span>Negative balance risk</span></div><strong>{forecast.negativeBalanceRisk ? 'Yes' : 'No'}</strong></article><article className="metric-card"><div className="metric-top"><span>Accounts</span></div><strong>{forecast.accounts.length}</strong></article><article className="metric-card"><div className="metric-top"><span>Forecast events</span></div><strong>{forecast.events.length}</strong></article></section><ForecastChart asOf={forecast.asOf} horizonEnd={forecast.horizonEnd} trajectory={forecast.trajectory} minimumDate={forecast.minimumFutureBalanceDate} currentBalance={forecast.accounts.reduce((sum, account) => sum + account.currentBalance, 0)} money={money} />{forecast.events.length ? <div className="transaction-list">{forecast.events.map((occurrence, index) => <div className="transaction" key={`${occurrence.date}-${occurrence.source}-${occurrence.recurringRuleId ?? occurrence.plannedTransactionId ?? index}`}><span className={`transaction-icon ${occurrence.transactionType === 'INCOME' ? 'green' : occurrence.transactionType === 'TRANSFER' ? 'purple' : 'blue'}`}>{occurrence.transactionType[0]}</span><span className="transaction-info"><strong>{occurrence.description ?? occurrence.transactionType}</strong><small>{occurrence.date} · <span className={`pill pill-${occurrence.status.toLowerCase()}`}>{occurrence.status}</span> <span className={`pill pill-${occurrence.source.toLowerCase()}`}>{occurrence.source}</span></small></span><strong className={occurrence.transactionType === 'INCOME' ? 'amount income-amount' : 'amount'}>{money.format(occurrence.amount)}</strong>{occurrence.source === 'RECURRING' && <button className="row-action" onClick={() => materializeOccurrence(occurrence)} type="button" aria-label="Materialize occurrence">+</button>}</div>)}</div> : <p className="empty-state">No forecast events in this horizon.</p>}</>}</section>
        <section className={`panel model-panel compliance-panel ${activeView === 'Compliance' ? 'visible-panel' : ''}`}><div className="panel-heading"><div><h2>Plan compliance</h2><p className="muted">{compliance ? `${compliance.from} → ${compliance.to} · actual vs. plan for the default plan` : 'How closely did reality follow the plan?'}</p></div><select aria-label="Compliance range" value={complianceMonths} onChange={event => setComplianceMonths(Number(event.target.value))}><option value={3}>Last 3 months</option><option value={6}>Last 6 months</option><option value={12}>Last 12 months</option><option value={24}>Last 24 months</option></select></div>
          {complianceLoading ? <p className="empty-state">Loading...</p> : !compliance ? <p className="empty-state">No compliance data available.</p> : <>
            <section className="metric-grid"><article className="metric-card"><div className="metric-top"><span>Planned income</span></div><strong>{money.format(compliance.totals.plannedIncome)}</strong></article><article className="metric-card"><div className="metric-top"><span>Actual income</span></div><strong>{money.format(compliance.totals.actualIncome)}</strong></article><article className="metric-card"><div className="metric-top"><span>Planned expense</span></div><strong>{money.format(compliance.totals.plannedExpense)}</strong></article><article className="metric-card"><div className="metric-top"><span>Actual expense</span></div><strong>{money.format(compliance.totals.actualExpense)}</strong></article><article className="metric-card"><div className="metric-top"><span>Net variance</span></div><strong className={compliance.totals.netVariance < 0 ? 'negative' : ''}>{money.format(compliance.totals.netVariance)}</strong></article><article className="metric-card"><div className="metric-top"><span>Categories on plan</span></div><strong>{compliance.totals.categoriesOnPlanRatio != null ? `${Math.round(compliance.totals.categoriesOnPlanRatio * 100)}%` : '—'}</strong></article></section>

            <div className="panel-heading"><div><h3>Where plan and reality diverge most</h3><p className="muted">Largest absolute variance, summed across the selected range</p></div></div>
            {topDivergences.length ? <div className="transaction-list">{topDivergences.map(item => { const favorability = favorabilityFor(item.categoryType, item.variance); return <div className="transaction" key={item.categoryId}><span className={`transaction-icon ${item.categoryType === 'Income' ? 'yellow' : 'green'}`}>{item.categoryName[0]}</span><span className="transaction-info"><strong>{item.categoryName}</strong><small>Planned {money.format(item.plannedAmount)} · Actual {money.format(item.actualAmount)} · <span className={`pill pill-${favorability.toLowerCase()}`}>{favorability}</span></small></span><strong className={item.variance > 0 ? 'amount income-amount' : 'amount'}>{item.variance > 0 ? '+' : ''}{money.format(item.variance)}</strong></div> })}</div> : <p className="empty-state">No planned or actual activity in this range.</p>}

            <div className="panel-heading"><div><h3>Month detail</h3></div><select aria-label="Compliance month" value={complianceSelectedPeriod} onChange={event => setComplianceSelectedPeriod(event.target.value)}>{compliance.periods.map(period => <option value={period.periodStart} key={period.periodStart}>{period.periodStart.slice(0, 7)} · {period.status}</option>)}</select></div>
            {selectedCompliancePeriod && <>
              {selectedCompliancePeriod.categories.length ? <div className="transaction-list">{selectedCompliancePeriod.categories.map(item => <div className="transaction" key={item.categoryId}><span className={`transaction-icon ${item.categoryType === 'Income' ? 'yellow' : 'green'}`}>{item.categoryName[0]}</span><span className="transaction-info"><strong>{item.categoryName}</strong><small>Planned {money.format(item.plannedAmount)} ({item.plannedRealCount}+{item.plannedRecurringCount}) · Actual {money.format(item.actualAmount)} ({item.actualMatchedCount} matched, {item.actualUnmatchedCount} unmatched){item.averageTimingVarianceDays != null ? ` · avg ${item.averageTimingVarianceDays.toFixed(1)}d late` : ''} · <span className={`pill pill-${item.favorability.toLowerCase()}`}>{item.favorability}</span></small></span><strong className={item.variance > 0 ? 'amount income-amount' : 'amount'}>{item.variance > 0 ? '+' : ''}{money.format(item.variance)}{item.variancePercent != null ? ` (${item.variancePercent > 0 ? '+' : ''}${item.variancePercent}%)` : ''}</strong></div>)}</div> : <p className="empty-state">No planned or actual activity for this month.</p>}
              {selectedCompliancePeriod.goals.length > 0 && <><div className="panel-heading"><div><h3>Goal contributions</h3><p className="muted">Planned vs. actual contribution amounts — separate from goal funding/feasibility status</p></div></div><div className="transaction-list goal-feasibility-list">{selectedCompliancePeriod.goals.map(goal => <div className="transaction" key={goal.goalId}><span className={`transaction-icon ${goal.priority === 'Hard' ? 'blue' : 'yellow'}`}>{goal.priority[0]}</span><span className="transaction-info"><strong>{goal.goalName}</strong><small>Planned {money.format(goal.plannedContribution)} · Actual {money.format(goal.actualContribution)} · <span className={`pill pill-${goal.favorability.toLowerCase()}`}>{goal.favorability}</span></small></span><strong className={goal.variance > 0 ? 'amount income-amount' : 'amount'}>{goal.variance > 0 ? '+' : ''}{money.format(goal.variance)}</strong></div>)}</div></>}
            </>}
          </>}
        </section>
        <section className={`panel model-panel categories-panel ${activeView === 'Categories' ? 'visible-panel' : ''}`}><div className="panel-heading"><div><h2>Categories</h2><p className="muted">{categories.length} active categories</p></div></div>{categories.length ? <div className="transaction-list">{categories.map(category => <div className="transaction" key={category.id}><span className={`transaction-icon ${category.type === 'Income' ? 'yellow' : 'green'}`}>{category.type[0]}</span><span className="transaction-info"><strong>{category.name}</strong><small>{category.type} · {category.active ? 'Active' : 'Inactive'}</small></span></div>)}</div> : <p className="empty-state">No categories configured.</p>}</section>
      </div></main>
    {showTransaction && <div className="modal-backdrop"><form className="modal" onSubmit={saveTransaction}><h2>{editingId ? 'Edit actual transaction' : 'Add actual transaction'}</h2><label>Description<input value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /></label><div className="form-row"><label>Amount<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={event => setForm({ ...form, amount: event.target.value })} /></label><label>Date<input required type="date" value={form.date} onChange={event => setForm({ ...form, date: event.target.value })} /></label></div><div className="form-row"><label>From account<select value={form.fromAccountId} onChange={event => setForm({ ...form, fromAccountId: event.target.value })}><option value="">External</option>{accounts.filter(account => account.active).map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label><label>To account<select value={form.toAccountId} onChange={event => setForm({ ...form, toAccountId: event.target.value })}><option value="">External</option>{accounts.filter(account => account.active).map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label></div><label>Category<select value={form.categoryId} onChange={event => setForm({ ...form, categoryId: event.target.value })}><option value="">No category</option>{categories.map(category => <option value={category.id} key={category.id}>{category.name} ({category.type})</option>)}</select></label><label>Planned transaction<select value={form.plannedTransactionId} onChange={event => setForm({ ...form, plannedTransactionId: event.target.value })}><option value="">No match</option>{planned.filter(item => !item.cancelled).map(item => <option value={item.id} key={item.id}>{item.description ?? item.transactionType} · {item.date} · {money.format(item.amount)}</option>)}</select></label><label>Goal<select value={form.goalId} onChange={event => setForm({ ...form, goalId: event.target.value })}><option value="">No goal</option>{goals.filter(goal => goal.active).map(goal => <option value={goal.id} key={goal.id}>{goal.name}</option>)}</select></label><button className="add-button full" disabled={saving} type="submit">{saving ? 'Saving...' : 'Save transaction'}</button></form></div>}
    {showAccount && <div className="modal-backdrop"><form className="modal" onSubmit={saveAccount}><h2>{editingAccountId ? 'Edit account' : 'Add account'}</h2><label>Name<input required value={accountName} onChange={event => setAccountName(event.target.value)} /></label><div className="form-row"><label>Currency<input required minLength={3} maxLength={3} value={currency} onChange={event => setCurrency(event.target.value.toUpperCase())} /></label><label>Opening balance<input min="0" step="0.01" type="number" value={openingBalance} onChange={event => setOpeningBalance(event.target.value)} /></label></div><button className="add-button full" disabled={saving} type="submit">{saving ? 'Saving...' : 'Save account'}</button></form></div>}
    {showPlanned && <div className="modal-backdrop"><form className="modal" onSubmit={savePlanned}><div className="modal-heading"><h2>{editingPlannedId ? 'Edit planned transaction' : 'Add planned transaction'}</h2><button className="close-button" onClick={closeForms} type="button" aria-label="Close">×</button></div><label>Description<input value={plannedForm.description} onChange={event => setPlannedForm({ ...plannedForm, description: event.target.value })} /></label><div className="form-row"><label>Amount<input required min="0.01" step="0.01" type="number" value={plannedForm.amount} onChange={event => setPlannedForm({ ...plannedForm, amount: event.target.value })} /></label><label>Date<input required type="date" value={plannedForm.date} onChange={event => setPlannedForm({ ...plannedForm, date: event.target.value })} /></label></div><div className="form-row"><label>From account<select value={plannedForm.fromAccountId} onChange={event => setPlannedForm({ ...plannedForm, fromAccountId: event.target.value })}><option value="">External</option>{accounts.filter(account => account.active).map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label><label>To account<select value={plannedForm.toAccountId} onChange={event => setPlannedForm({ ...plannedForm, toAccountId: event.target.value })}><option value="">External</option>{accounts.filter(account => account.active).map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label></div><label>Category<select value={plannedForm.categoryId} onChange={event => setPlannedForm({ ...plannedForm, categoryId: event.target.value })}><option value="">No category</option>{categories.map(category => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>Goal<select value={plannedForm.goalId} onChange={event => setPlannedForm({ ...plannedForm, goalId: event.target.value })}><option value="">No goal</option>{goals.filter(goal => goal.active).map(goal => <option value={goal.id} key={goal.id}>{goal.name}</option>)}</select></label><button className="add-button full" disabled={saving} type="submit">{saving ? 'Saving...' : 'Save planned transaction'}</button></form></div>}
    {showRecurring && <div className="modal-backdrop"><form className="modal" onSubmit={saveRecurring}><div className="modal-heading"><h2>{editingRecurringId ? 'Edit recurring rule' : 'Add recurring rule'}</h2><button className="close-button" onClick={closeForms} type="button" aria-label="Close">×</button></div><label>Name<input required value={recurringForm.name} onChange={event => setRecurringForm({ ...recurringForm, name: event.target.value })} /></label><label>Description<input value={recurringForm.description} onChange={event => setRecurringForm({ ...recurringForm, description: event.target.value })} /></label><div className="form-row"><label>Amount<input required min="0.01" step="0.01" type="number" value={recurringForm.amount} onChange={event => setRecurringForm({ ...recurringForm, amount: event.target.value })} /></label><label>Frequency<select value={recurringForm.frequency} onChange={event => setRecurringForm({ ...recurringForm, frequency: event.target.value })}><option value="Daily">Daily</option><option value="Weekly">Weekly</option><option value="Monthly">Monthly</option><option value="Yearly">Yearly</option></select></label></div><div className="form-row"><label>Start date<input required type="date" value={recurringForm.startDate} onChange={event => setRecurringForm({ ...recurringForm, startDate: event.target.value })} /></label><label>Day of month<input min="1" max="31" type="number" value={recurringForm.dayOfMonth} onChange={event => setRecurringForm({ ...recurringForm, dayOfMonth: event.target.value })} /></label></div><label>End date (optional)<input type="date" min={recurringForm.startDate || undefined} value={recurringForm.endDate} onChange={event => setRecurringForm({ ...recurringForm, endDate: event.target.value })} /></label><div className="form-row"><label>From account<select value={recurringForm.fromAccountId} onChange={event => setRecurringForm({ ...recurringForm, fromAccountId: event.target.value })}><option value="">External</option>{accounts.filter(account => account.active).map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label><label>To account<select value={recurringForm.toAccountId} onChange={event => setRecurringForm({ ...recurringForm, toAccountId: event.target.value })}><option value="">External</option>{accounts.filter(account => account.active).map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label></div><label>Category<select value={recurringForm.categoryId} onChange={event => setRecurringForm({ ...recurringForm, categoryId: event.target.value })}><option value="">No category</option>{categories.map(category => <option value={category.id} key={category.id}>{category.name} ({category.type})</option>)}</select></label><button className="add-button full" disabled={saving} type="submit">{saving ? 'Saving...' : editingRecurringId ? 'Save changes' : 'Save recurring rule'}</button></form></div>}
    {showCategory && <div className="modal-backdrop"><form className="modal" onSubmit={saveCategory}><div className="modal-heading"><h2>Add category</h2><button className="close-button" onClick={closeForms} type="button" aria-label="Close">×</button></div><label>Name<input required value={categoryName} onChange={event => setCategoryName(event.target.value)} /></label><label>Type<select value={categoryType} onChange={event => setCategoryType(event.target.value)}><option value="Income">Income</option><option value="Expense">Expense</option></select></label><button className="add-button full" disabled={saving} type="submit">{saving ? 'Saving...' : 'Save category'}</button></form></div>}
    {showGoal && <div className="modal-backdrop"><form className="modal" onSubmit={saveGoal}><div className="modal-heading"><h2>{editingGoalId ? 'Edit goal' : 'Add goal'}</h2><button className="close-button" onClick={closeForms} type="button" aria-label="Close">×</button></div><label>Name<input required value={goalForm.name} onChange={event => setGoalForm({ ...goalForm, name: event.target.value })} /></label><label>Description<input value={goalForm.description} onChange={event => setGoalForm({ ...goalForm, description: event.target.value })} /></label><div className="form-row"><label>Target amount<input required min="0.01" step="0.01" type="number" value={goalForm.targetAmount} onChange={event => setGoalForm({ ...goalForm, targetAmount: event.target.value })} /></label><label>Target date<input required type="date" value={goalForm.targetDate} onChange={event => setGoalForm({ ...goalForm, targetDate: event.target.value })} /></label></div><div className="form-row"><label>Priority<select value={goalForm.priority} onChange={event => setGoalForm({ ...goalForm, priority: event.target.value as 'Hard' | 'Soft' })}><option value="Soft">Soft</option><option value="Hard">Hard</option></select></label><label>Funding recurring rule<select value={goalForm.recurringRuleId} onChange={event => setGoalForm({ ...goalForm, recurringRuleId: event.target.value })}><option value="">None</option>{recurring.map(rule => <option value={rule.id} key={rule.id}>{rule.name}</option>)}</select></label></div><button className="add-button full" disabled={saving} type="submit">{saving ? 'Saving...' : 'Save goal'}</button></form></div>}
  </div>
}
export default App
