DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'finplanner') THEN
        CREATE SCHEMA finplanner;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS finplanner."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'finplanner') THEN
        CREATE SCHEMA finplanner;
    END IF;
END $EF$;

CREATE TABLE finplanner.account (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    currency character(3) NOT NULL,
    opening_balance numeric(14,2) NOT NULL DEFAULT 0.0,
    active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_account" PRIMARY KEY (id),
    CONSTRAINT account_currency_chk CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE TABLE finplanner.category (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    type character varying(10) NOT NULL,
    active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_category" PRIMARY KEY (id),
    CONSTRAINT category_type_chk CHECK (type IN ('INCOME', 'EXPENSE'))
);

CREATE TABLE finplanner.recurring_rule (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    from_account_id bigint,
    to_account_id bigint,
    category_id bigint,
    amount numeric(14,2) NOT NULL,
    frequency character varying(10) NOT NULL,
    day_of_month smallint,
    start_date date NOT NULL,
    end_date date,
    active boolean NOT NULL DEFAULT TRUE,
    description text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_recurring_rule" PRIMARY KEY (id),
    CONSTRAINT recurring_account_chk CHECK (from_account_id IS NOT NULL OR to_account_id IS NOT NULL),
    CONSTRAINT recurring_amount_chk CHECK (amount > 0),
    CONSTRAINT recurring_dates_chk CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT recurring_day_chk CHECK (day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31),
    CONSTRAINT recurring_frequency_chk CHECK (frequency IN ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY')),
    CONSTRAINT recurring_same_account_chk CHECK (from_account_id IS NULL OR to_account_id IS NULL OR from_account_id <> to_account_id),
    CONSTRAINT recurring_transfer_category_chk CHECK ((from_account_id IS NOT NULL AND to_account_id IS NOT NULL AND category_id IS NULL) OR NOT (from_account_id IS NOT NULL AND to_account_id IS NOT NULL)),
    CONSTRAINT "FK_recurring_rule_account_from_account_id" FOREIGN KEY (from_account_id) REFERENCES finplanner.account (id),
    CONSTRAINT "FK_recurring_rule_account_to_account_id" FOREIGN KEY (to_account_id) REFERENCES finplanner.account (id),
    CONSTRAINT "FK_recurring_rule_category_category_id" FOREIGN KEY (category_id) REFERENCES finplanner.category (id)
);

CREATE TABLE finplanner.planned_transaction (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    planned_date date NOT NULL,
    amount numeric(14,2) NOT NULL,
    from_account_id bigint,
    to_account_id bigint,
    category_id bigint,
    recurring_rule_id bigint,
    description text,
    cancelled boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_planned_transaction" PRIMARY KEY (id),
    CONSTRAINT planned_account_chk CHECK (from_account_id IS NOT NULL OR to_account_id IS NOT NULL),
    CONSTRAINT planned_amount_chk CHECK (amount > 0),
    CONSTRAINT planned_same_account_chk CHECK (from_account_id IS NULL OR to_account_id IS NULL OR from_account_id <> to_account_id),
    CONSTRAINT planned_transfer_category_chk CHECK ((from_account_id IS NOT NULL AND to_account_id IS NOT NULL AND category_id IS NULL) OR NOT (from_account_id IS NOT NULL AND to_account_id IS NOT NULL)),
    CONSTRAINT "FK_planned_transaction_account_from_account_id" FOREIGN KEY (from_account_id) REFERENCES finplanner.account (id),
    CONSTRAINT "FK_planned_transaction_account_to_account_id" FOREIGN KEY (to_account_id) REFERENCES finplanner.account (id),
    CONSTRAINT "FK_planned_transaction_category_category_id" FOREIGN KEY (category_id) REFERENCES finplanner.category (id),
    CONSTRAINT "FK_planned_transaction_recurring_rule_recurring_rule_id" FOREIGN KEY (recurring_rule_id) REFERENCES finplanner.recurring_rule (id)
);

CREATE TABLE finplanner.actual_transaction (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    actual_date date NOT NULL,
    amount numeric(14,2) NOT NULL,
    from_account_id bigint,
    to_account_id bigint,
    category_id bigint,
    planned_transaction_id bigint,
    description text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_actual_transaction" PRIMARY KEY (id),
    CONSTRAINT actual_account_chk CHECK (from_account_id IS NOT NULL OR to_account_id IS NOT NULL),
    CONSTRAINT actual_amount_chk CHECK (amount > 0),
    CONSTRAINT actual_same_account_chk CHECK (from_account_id IS NULL OR to_account_id IS NULL OR from_account_id <> to_account_id),
    CONSTRAINT actual_transfer_category_chk CHECK ((from_account_id IS NOT NULL AND to_account_id IS NOT NULL AND category_id IS NULL) OR NOT (from_account_id IS NOT NULL AND to_account_id IS NOT NULL)),
    CONSTRAINT "FK_actual_transaction_account_from_account_id" FOREIGN KEY (from_account_id) REFERENCES finplanner.account (id),
    CONSTRAINT "FK_actual_transaction_account_to_account_id" FOREIGN KEY (to_account_id) REFERENCES finplanner.account (id),
    CONSTRAINT "FK_actual_transaction_category_category_id" FOREIGN KEY (category_id) REFERENCES finplanner.category (id),
    CONSTRAINT "FK_actual_transaction_planned_transaction_planned_transaction_~" FOREIGN KEY (planned_transaction_id) REFERENCES finplanner.planned_transaction (id)
);

CREATE INDEX "IX_actual_transaction_category_id" ON finplanner.actual_transaction (category_id);

CREATE INDEX "IX_actual_transaction_from_account_id" ON finplanner.actual_transaction (from_account_id);

CREATE INDEX "IX_actual_transaction_planned_transaction_id" ON finplanner.actual_transaction (planned_transaction_id);

CREATE INDEX "IX_actual_transaction_to_account_id" ON finplanner.actual_transaction (to_account_id);

CREATE UNIQUE INDEX category_name_uq ON finplanner.category (name);

CREATE INDEX "IX_planned_transaction_category_id" ON finplanner.planned_transaction (category_id);

CREATE INDEX "IX_planned_transaction_from_account_id" ON finplanner.planned_transaction (from_account_id);

CREATE INDEX "IX_planned_transaction_recurring_rule_id" ON finplanner.planned_transaction (recurring_rule_id);

CREATE INDEX "IX_planned_transaction_to_account_id" ON finplanner.planned_transaction (to_account_id);

CREATE INDEX "IX_recurring_rule_category_id" ON finplanner.recurring_rule (category_id);

CREATE INDEX "IX_recurring_rule_from_account_id" ON finplanner.recurring_rule (from_account_id);

CREATE INDEX "IX_recurring_rule_to_account_id" ON finplanner.recurring_rule (to_account_id);

CREATE INDEX idx_planned_transaction_date ON finplanner.planned_transaction (planned_date);

CREATE INDEX idx_planned_transaction_from_account ON finplanner.planned_transaction (from_account_id);

CREATE INDEX idx_planned_transaction_to_account ON finplanner.planned_transaction (to_account_id);

CREATE INDEX idx_planned_transaction_recurring_rule ON finplanner.planned_transaction (recurring_rule_id);

CREATE INDEX idx_actual_transaction_date ON finplanner.actual_transaction (actual_date);

CREATE INDEX idx_actual_transaction_from_account ON finplanner.actual_transaction (from_account_id);

CREATE INDEX idx_actual_transaction_to_account ON finplanner.actual_transaction (to_account_id);

CREATE INDEX idx_actual_transaction_planned ON finplanner.actual_transaction (planned_transaction_id);

CREATE UNIQUE INDEX uq_actual_transaction_planned ON finplanner.actual_transaction (planned_transaction_id) WHERE planned_transaction_id IS NOT NULL;

CREATE VIEW finplanner.transaction_timeline AS
SELECT p.id AS planned_transaction_id, a.id AS actual_transaction_id,
       p.planned_date, a.actual_date, p.amount AS planned_amount, a.amount AS actual_amount,
       CASE WHEN p.amount IS NOT NULL AND a.amount IS NOT NULL THEN a.amount - p.amount ELSE NULL END AS amount_variance,
       p.from_account_id AS planned_from_account_id, p.to_account_id AS planned_to_account_id,
       a.from_account_id AS actual_from_account_id, a.to_account_id AS actual_to_account_id,
       p.category_id AS planned_category_id, a.category_id AS actual_category_id,
       p.recurring_rule_id, p.description AS planned_description, a.description AS actual_description,
       CASE WHEN p.id IS NOT NULL AND a.id IS NOT NULL THEN 'MATCHED'
            WHEN p.id IS NOT NULL AND a.id IS NULL THEN CASE WHEN p.cancelled THEN 'CANCELLED' WHEN p.planned_date < CURRENT_DATE THEN 'OVERDUE' ELSE 'PLANNED' END
            WHEN p.id IS NULL AND a.id IS NOT NULL THEN 'UNPLANNED' END AS status,
       CASE WHEN COALESCE(p.from_account_id, a.from_account_id) IS NOT NULL AND COALESCE(p.to_account_id, a.to_account_id) IS NOT NULL THEN 'TRANSFER'
            WHEN COALESCE(p.from_account_id, a.from_account_id) IS NULL AND COALESCE(p.to_account_id, a.to_account_id) IS NOT NULL THEN 'INCOME'
            WHEN COALESCE(p.from_account_id, a.from_account_id) IS NOT NULL AND COALESCE(p.to_account_id, a.to_account_id) IS NULL THEN 'EXPENSE' END AS transaction_type
FROM finplanner.planned_transaction p
FULL OUTER JOIN finplanner.actual_transaction a ON a.planned_transaction_id = p.id;

INSERT INTO finplanner."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260911173644_InitialFinalModel', '10.0.11');

COMMIT;

